# Generated by Django 5.0.4 on 2024-05-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoctaCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('rasgo1', models.CharField(max_length=200)),
                ('rasgo2', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('vida', models.IntegerField()),
                ('mana', models.IntegerField()),
                ('dano', models.IntegerField()),
                ('skin', models.BooleanField(default=False)),
                ('edicion', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=1000)),
            ],
        ),
    ]
